### ISSUE TITLE
Version 1.0?

### ISSUE THREAD

**Issue by Nyholm** [Nyholm/psr7-server#11]
Are we happy with this interface?

@Zegnat ?

**Comment by Zegnat** [comment]
I was trying to set this up and got to wondering whether it is right to limit `ServerRequestCreatorInterface::fromGlobals` to `getallheaders` for the HTTP headers?

That method is, generally, only available on Apache servers. Anyone currently using this implementation who cannot guarantee their code will run in an Apache environment will have to do something [like I had to do](https://github.com/Zegnat/php-website-starter/blob/df62b66c881e90a757126e19853ae47b418bbda8/public/index.php#L30-L59):

``` php
$requestCreator = $injector->make(Nyholm\Psr7Server\ServerRequestCreator::class);
$request = $requestCreator->fromArrays(
    $_SERVER,
    function_exists('getallheaders') ? getallheaders() : $requestCreator->getHeadersFromServer($_SERVER),
    $_COOKIE,
    $_GET,
    $_POST,
    $_FILES
);
```

As the interface is already defining a method for getting headers from globals, why not use that?

On that note, if `ServerRequestCreatorInterface::getHeadersFromServer` is supposed to fill the polyfill-for-non-Apache role, would it be better as a `static` method? That way it could truly be used as a polyfill in other circumstances too without always having to create a new `ServerRequestCreatorInterface` instance.

**Comment by Nyholm** [comment]
It makes sense to fall back on `getHeadersFromServer` if `getallheaders()` is not available 👍 

Sure, we can declare it static. Would you mind creating a PR?

**Comment by Zegnat** [comment]
PRs filed, new issue opened. Basically detailing things I personally would have expected `ServerRequestCreatorInterface::fromGlobals` to do but found it didn’t do.

**Comment by mindplay-dk** [comment]
Are there any pending issues blocking a 1.0 release?

If so, I'm happy to help. If not... :-)
