### ISSUE TITLE
Should fromGlobals also set the HTTP request body?

### ISSUE THREAD

**Issue by Zegnat** [Nyholm/psr7-server#15]
This is another thing developers likely want for the ServerRequest object: the request body. PHP puts this away [in `php://input`](https://secure.php.net/manual/en/wrappers.php.php#wrappers.php.input). Currently you would need to [pass a stream](https://github.com/Zegnat/php-website-starter/blob/8b8bf25fd5d83d133f6a49b0f3bb6b9cb197006b/public/index.php#L58) to the `fromArrays` method:

```php
$requestBody = fopen('php://input', 'r');
```

Should `fromGlobals` be extended with something like “defaults to php://input as body”?

**Comment by Nyholm** [comment]
Yes. It should. 
I forgot about that when I was adding the body argument. 

:+1:
