### ISSUE TITLE
Better Namespaces

### ISSUE THREAD

**Issue by designermonkey** [Nyholm/psr7-server#30]
Would it not make more sense to have `Nyholm\Psr7\Server` to follow the other packages you have?

**Comment by Zegnat** [comment]
`Nyholm\Psr7` only contains classes that have been defined by PHP-FIG. I think it would be a mistake if we were to add a class to that namespace. Especially if it would be taking a spot of something PHP-FIG may specify in the future.

Much safer to keep it separated, IMHO.

**Comment by Nyholm** [comment]
I agree with @Zegnat. Thank you for the suggestion though.

**Comment by designermonkey** [comment]
I'm confused as to what the PHP-FIG has to do with your namespace, but ok.
